/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class moe_kyokobot_libdave_natives_DaveNativeBindings */

#ifndef _Included_moe_kyokobot_libdave_natives_DaveNativeBindings
#define _Included_moe_kyokobot_libdave_natives_DaveNativeBindings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveMaxSupportedProtocolVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveMaxSupportedProtocolVersion
  (JNIEnv *, jobject);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveSessionCreate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lmoe/kyokobot/libdave/callbacks/MLSFailureCallback;)J
 */
JNIEXPORT jlong JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveSessionCreate
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveSessionDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveSessionDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveSessionInit
 * Signature: (JIJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveSessionInit
  (JNIEnv *, jobject, jlong, jint, jlong, jstring);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveSessionReset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveSessionReset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveSessionSetProtocolVersion
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveSessionSetProtocolVersion
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveSessionGetProtocolVersion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveSessionGetProtocolVersion
  (JNIEnv *, jobject, jlong);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveSessionGetLastEpochAuthenticator
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveSessionGetLastEpochAuthenticator
  (JNIEnv *, jobject, jlong);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveSessionSetExternalSender
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveSessionSetExternalSender
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveSessionProcessProposals
 * Signature: (J[B[Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveSessionProcessProposals
  (JNIEnv *, jobject, jlong, jbyteArray, jobjectArray);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveSessionProcessCommit
 * Signature: (J[B)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveSessionProcessCommit
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveSessionProcessWelcome
 * Signature: (J[B[Ljava/lang/String;)Lmoe/kyokobot/libdave/RosterMap;
 */
JNIEXPORT jobject JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveSessionProcessWelcome
  (JNIEnv *, jobject, jlong, jbyteArray, jobjectArray);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveSessionGetMarshalledKeyPackage
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveSessionGetMarshalledKeyPackage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveSessionGetKeyRatchet
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveSessionGetKeyRatchet
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveSessionGetPairwiseFingerprint
 * Signature: (JILjava/lang/String;Ljava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveSessionGetPairwiseFingerprint
  (JNIEnv *, jobject, jlong, jint, jstring, jobject);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveKeyRatchetGetEncryptionKey
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveKeyRatchetGetEncryptionKey
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveKeyRatchetDeleteKey
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveKeyRatchetDeleteKey
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveKeyRatchetDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveKeyRatchetDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveEncryptorCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveEncryptorCreate
  (JNIEnv *, jobject);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveEncryptorDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveEncryptorDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveEncryptorSetKeyRatchet
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveEncryptorSetKeyRatchet
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveEncryptorSetPassthroughMode
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveEncryptorSetPassthroughMode
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveEncryptorAssignSsrcToCodec
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveEncryptorAssignSsrcToCodec
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveEncryptorGetProtocolVersion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveEncryptorGetProtocolVersion
  (JNIEnv *, jobject, jlong);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveEncryptorGetMaxCiphertextByteSize
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveEncryptorGetMaxCiphertextByteSize
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveEncryptorEncrypt
 * Signature: (JII[B[B)I
 */
JNIEXPORT jint JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveEncryptorEncrypt__JII_3B_3B
  (JNIEnv *, jobject, jlong, jint, jint, jbyteArray, jbyteArray);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveEncryptorEncrypt
 * Signature: (JIILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveEncryptorEncrypt__JIILjava_nio_ByteBuffer_2Ljava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jint, jint, jobject, jobject);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveEncryptorEncrypt
 * Signature: (JIIJIJI)I
 */
JNIEXPORT jint JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveEncryptorEncrypt__JIIJIJI
  (JNIEnv *, jobject, jlong, jint, jint, jlong, jint, jlong, jint);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveEncryptorSetProtocolVersionChangedCallback
 * Signature: (JLmoe/kyokobot/libdave/callbacks/EncryptorProtocolVersionChangedCallback;)V
 */
JNIEXPORT void JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveEncryptorSetProtocolVersionChangedCallback
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveDecryptorCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveDecryptorCreate
  (JNIEnv *, jobject);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveDecryptorDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveDecryptorDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveDecryptorTransitionToKeyRatchet
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveDecryptorTransitionToKeyRatchet
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveDecryptorTransitionToPassthroughMode
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveDecryptorTransitionToPassthroughMode
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveDecryptorDecrypt
 * Signature: (JI[B[B)I
 */
JNIEXPORT jint JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveDecryptorDecrypt__JI_3B_3B
  (JNIEnv *, jobject, jlong, jint, jbyteArray, jbyteArray);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveDecryptorDecrypt
 * Signature: (JILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveDecryptorDecrypt__JILjava_nio_ByteBuffer_2Ljava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jint, jobject, jobject);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveDecryptorDecrypt
 * Signature: (JIJIJI)I
 */
JNIEXPORT jint JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveDecryptorDecrypt__JIJIJI
  (JNIEnv *, jobject, jlong, jint, jlong, jint, jlong, jint);

/*
 * Class:     moe_kyokobot_libdave_natives_DaveNativeBindings
 * Method:    daveDecryptorGetMaxPlaintextByteSize
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_moe_kyokobot_libdave_natives_DaveNativeBindings_daveDecryptorGetMaxPlaintextByteSize
  (JNIEnv *, jobject, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
