
# include(${CMAKE_CURRENT_LIST_DIR}/OpenSSLTargets.cmake)
set(OPENSSL_ROOT_DIR "${CMAKE_SOURCE_DIR}/boringssl")

set(BORINGSSL_OUTPUT_DIR "${CMAKE_BINARY_DIR}/boringssl")
set(OPENSSL_INCLUDE_DIR "${OPENSSL_ROOT_DIR}/include")

if(MSVC)
    set(OPENSSL_SSL_LIBRARY "${BORINGSSL_OUTPUT_DIR}/ssl.lib")
    set(OPENSSL_CRYPTO_LIBRARY "${BORINGSSL_OUTPUT_DIR}/crypto.lib")
else()
    set(OPENSSL_SSL_LIBRARY "${BORINGSSL_OUTPUT_DIR}/libssl.a")
    set(OPENSSL_CRYPTO_LIBRARY "${BORINGSSL_OUTPUT_DIR}/libcrypto.a")
endif()

# set(OPENSSL_CRYPTO_LIBRARY crypto)
# set(OPENSSL_SSL_LIBRARY ssl)

set(OPENSSL_SSL_LIBRARIES ${OPENSSL_SSL_LIBRARY})
set(OPENSSL_CRYPTO_LIBRARIES ${OPENSSL_CRYPTO_LIBRARY})
set(OPENSSL_LIBRARIES ${OPENSSL_CRYPTO_LIBRARY} ${OPENSSL_SSL_LIBRARY})

# set(BORINGSSL_INCLUDE_DIR ${OPENSSL_INCLUDE_DIR})
# check_required_components(OpenSSL)

set(OPENSSL_FOUND YES)
set(OpenSSL_VERSION "1.1.1")
set(OpenSSL_FOUND YES)
set(OpenSSL_SSL_FOUND YES)
set(OpenSSL_Crypto_FOUND YES)

message(STATUS "OPENSSL_ROOT_DIR: ${OPENSSL_ROOT_DIR}")
message(STATUS "OPENSSL_INCLUDE_DIR: ${OPENSSL_INCLUDE_DIR}")
message(STATUS "OPENSSL_CRYPTO_LIBRARY: ${OPENSSL_CRYPTO_LIBRARY}")
message(STATUS "OPENSSL_SSL_LIBRARY: ${OPENSSL_SSL_LIBRARY}")

if(NOT TARGET OpenSSL::SSL)
    add_library(OpenSSL::SSL STATIC IMPORTED GLOBAL)
    set_target_properties(OpenSSL::SSL PROPERTIES
        IMPORTED_LOCATION "${OPENSSL_SSL_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_INCLUDE_DIR}"
    )
endif()

if(NOT TARGET OpenSSL::Crypto)
    add_library(OpenSSL::Crypto STATIC IMPORTED GLOBAL)
    set_target_properties(OpenSSL::Crypto PROPERTIES
        IMPORTED_LOCATION "${OPENSSL_CRYPTO_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_INCLUDE_DIR}"
    )
endif()