# x86_64 Linux with musl.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)
set(CMAKE_STRIP strip)
set(CMAKE_C_COMPILER_TARGET x86_64-linux-musl)
set(CMAKE_CXX_COMPILER_TARGET x86_64-linux-musl)
if(EXISTS "/usr/x86_64-linux-musl")
  set(CMAKE_SYSROOT "/usr/x86_64-linux-musl")
  set(CMAKE_FIND_ROOT_PATH "/usr/x86_64-linux-musl")
endif()