# armhf Linux with musl.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv7l)
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_STRIP llvm-strip)
set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_C_COMPILER_TARGET arm-linux-musleabihf)
set(CMAKE_CXX_COMPILER_TARGET arm-linux-musleabihf)
if(EXISTS "/usr/arm-linux-musleabihf")
  # Prefer an explicit musl sysroot when available (required for crt/libc discovery).
  set(CMAKE_SYSROOT "/usr/arm-linux-musleabihf")
  set(CMAKE_FIND_ROOT_PATH "/usr/arm-linux-musleabihf")
endif()
