# 32-bit x86 Linux (glibc). Use with multilib (-m32) on x86_64 host.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR i686)
set(BOOTLIN_DIR "/opt/toolchains/x86-i686--glibc--stable-2024.05-1")
set(BOOTLIN_PREFIX "i686-buildroot-linux-gnu")

if(EXISTS "${BOOTLIN_DIR}")
  set(CMAKE_C_COMPILER "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-gcc")
  set(CMAKE_CXX_COMPILER "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-g++")
  set(CMAKE_STRIP "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-strip")
  set(CMAKE_AR "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-gcc-ar")
  set(CMAKE_NM "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-gcc-nm")
  set(CMAKE_RANLIB "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-gcc-ranlib")
  set(CMAKE_SYSROOT "${BOOTLIN_DIR}/${BOOTLIN_PREFIX}/sysroot")
  set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -msse2")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -msse2")
else()
  set(CMAKE_C_COMPILER gcc)
  set(CMAKE_CXX_COMPILER g++)
  set(CMAKE_STRIP strip)
  set(CMAKE_AR gcc-ar)
  set(CMAKE_NM gcc-nm)
  set(CMAKE_RANLIB gcc-ranlib)
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -m32 -msse2")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -m32 -msse2")
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -m32")
  set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -m32")
  if(EXISTS "/usr/i686-linux-gnu")
    set(CMAKE_SYSROOT "/usr/i686-linux-gnu")
    set(CMAKE_FIND_ROOT_PATH "/usr/i686-linux-gnu")
  endif()
endif()