# aarch64 Linux with musl.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)
set(CMAKE_STRIP strip)
set(CMAKE_C_COMPILER_TARGET aarch64-linux-musl)
set(CMAKE_CXX_COMPILER_TARGET aarch64-linux-musl)
if(EXISTS "/usr/aarch64-linux-musl")
  set(CMAKE_SYSROOT "/usr/aarch64-linux-musl")
  set(CMAKE_FIND_ROOT_PATH "/usr/aarch64-linux-musl")
endif()