# Cross-compile for aarch64 Linux (glibc).
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(BOOTLIN_DIR "/opt/toolchains/aarch64--glibc--stable-2024.05-1")
set(BOOTLIN_PREFIX "aarch64-buildroot-linux-gnu")

if(EXISTS "${BOOTLIN_DIR}")
  set(CMAKE_C_COMPILER "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-gcc")
  set(CMAKE_CXX_COMPILER "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-g++")
  set(CMAKE_STRIP "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-strip")
  set(CMAKE_SYSROOT "${BOOTLIN_DIR}/${BOOTLIN_PREFIX}/sysroot")
  set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
else()
  set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
  set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)
  set(CMAKE_STRIP aarch64-linux-gnu-strip)
  if(EXISTS "/usr/aarch64-linux-gnu")
    set(CMAKE_SYSROOT "/usr/aarch64-linux-gnu")
    set(CMAKE_FIND_ROOT_PATH "/usr/aarch64-linux-gnu")
  endif()
endif()