# Cross-compile for armhf Linux (glibc).
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv7l)
set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)
set(CMAKE_STRIP strip)
set(CMAKE_C_COMPILER_TARGET arm-linux-gnueabihf)
set(CMAKE_CXX_COMPILER_TARGET arm-linux-gnueabihf)
if(EXISTS "/usr/arm-linux-gnueabihf")
  set(CMAKE_SYSROOT "/usr/arm-linux-gnueabihf")
  set(CMAKE_FIND_ROOT_PATH "/usr/arm-linux-gnueabihf")
endif()