# x86_64 Linux with musl.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(BOOTLIN_DIR "/opt/toolchains/x86-64--musl--stable-2024.05-1")
set(BOOTLIN_PREFIX "x86_64-buildroot-linux-musl")

if(EXISTS "${BOOTLIN_DIR}")
  set(CMAKE_C_COMPILER "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-gcc")
  set(CMAKE_CXX_COMPILER "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-g++")
  set(CMAKE_STRIP "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-strip")
  set(CMAKE_SYSROOT "${BOOTLIN_DIR}/${BOOTLIN_PREFIX}/sysroot")
  set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
else()
  set(CMAKE_C_COMPILER gcc)
  set(CMAKE_CXX_COMPILER g++)
  set(CMAKE_STRIP strip)
  if(EXISTS "/usr/x86_64-linux-musl")
    set(CMAKE_SYSROOT "/usr/x86_64-linux-musl")
    set(CMAKE_FIND_ROOT_PATH "/usr/x86_64-linux-musl")
  endif()
endif()