# Native or generic x86_64 Linux (glibc). Use on ubuntu-22.04 runner without cross-compilation.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_STRIP llvm-strip)
set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_C_COMPILER_TARGET x86_64-linux-gnu)
set(CMAKE_CXX_COMPILER_TARGET x86_64-linux-gnu)
if(EXISTS "/usr/x86_64-linux-gnu")
  set(CMAKE_SYSROOT "/usr/x86_64-linux-gnu")
  set(CMAKE_FIND_ROOT_PATH "/usr/x86_64-linux-gnu")
endif()