# Cross-compile for armhf Linux (glibc).
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv7l)
set(BOOTLIN_DIR "/opt/toolchains/armv7-eabihf--glibc--stable-2022.08-1")
set(BOOTLIN_PREFIX "arm-buildroot-linux-gnueabihf")

if(EXISTS "${BOOTLIN_DIR}")
  set(CMAKE_C_COMPILER "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-gcc")
  set(CMAKE_CXX_COMPILER "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-g++")
  set(CMAKE_STRIP "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-strip")
  set(CMAKE_AR "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-gcc-ar")
  set(CMAKE_NM "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-gcc-nm")
  set(CMAKE_RANLIB "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-gcc-ranlib")
  set(CMAKE_SYSROOT "${BOOTLIN_DIR}/${BOOTLIN_PREFIX}/sysroot")
  set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
else()
  set(CMAKE_C_COMPILER arm-linux-gnueabihf-gcc)
  set(CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++)
  set(CMAKE_STRIP arm-linux-gnueabihf-strip)
  set(CMAKE_AR arm-linux-gnueabihf-gcc-ar)
  set(CMAKE_NM arm-linux-gnueabihf-gcc-nm)
  set(CMAKE_RANLIB arm-linux-gnueabihf-gcc-ranlib)
  if(EXISTS "/usr/arm-linux-gnueabihf")
    set(CMAKE_SYSROOT "/usr/arm-linux-gnueabihf")
    set(CMAKE_FIND_ROOT_PATH "/usr/arm-linux-gnueabihf")
  endif()
endif()