# armhf Linux with musl.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv7l)
set(BOOTLIN_DIR "/opt/toolchains/armv7-eabihf--musl--stable-2024.05-1")
set(BOOTLIN_PREFIX "arm-buildroot-linux-musleabihf")

if(EXISTS "${BOOTLIN_DIR}")
  set(CMAKE_C_COMPILER "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-gcc")
  set(CMAKE_CXX_COMPILER "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-g++")
  set(CMAKE_STRIP "${BOOTLIN_DIR}/bin/${BOOTLIN_PREFIX}-strip")
  set(CMAKE_SYSROOT "${BOOTLIN_DIR}/${BOOTLIN_PREFIX}/sysroot")
  set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
else()
  set(CMAKE_C_COMPILER arm-linux-gnueabihf-gcc)
  set(CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++)
  set(CMAKE_STRIP arm-linux-gnueabihf-strip)
  if(EXISTS "/usr/arm-linux-musleabihf")
    set(CMAKE_SYSROOT "/usr/arm-linux-musleabihf")
    set(CMAKE_FIND_ROOT_PATH "/usr/arm-linux-musleabihf")
  endif()
endif()
