# armhf Linux with musl.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv7l)
set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)
set(CMAKE_STRIP strip)
set(CMAKE_C_COMPILER_TARGET arm-linux-musleabihf)
set(CMAKE_CXX_COMPILER_TARGET arm-linux-musleabihf)
if(EXISTS "/usr/arm-linux-musleabihf")
  set(CMAKE_SYSROOT "/usr/arm-linux-musleabihf")
  set(CMAKE_FIND_ROOT_PATH "/usr/arm-linux-musleabihf")
endif()
